### ISSUE TITLE
SLF4J error

### ISSUE THREAD

**Issue by dvreed77** [graphframes/graphframes#113]
I am running Scala 2.10.4 with Spark 1.5.0-cdh5.5.2 and am getting the following error when running a GraphFrames job:

scala

```
> val g = GraphFrame(v, e)
error: bad symbolic reference. A signature in Logging.class refers to type LazyLogging
in package com.typesafe.scalalogging.slf4j which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling Logging.class.
```

I am starting my spark-shell with the following command:

`spark-shell --jars /data/spark-jars/scalalogging-slf4j_2.10-1.1.0.jar,/data/spark-jars/graphframes-0.2.0-spark1.5-s_2.10.jar`

I have tried different versions of scalalogging, but nothing seems to work.

Thanks for the help.

**Comment by thunterdb** [comment]
@dvreed77 we use the following package: `"com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2"`, which you can use with `spark-shell` 's `--package` option

**Comment by hxu** [comment]
This has broken the Python side APIs as well.  Should this not be packaged with the main graphframes jar?

**Comment by hxu** [comment]
To get this working, I had to include both `scala-logging-slf4j` and `scala-logging-api` at version 2.1.2.  I set this by adding them to the `--jars` option to `spark-submit`

**Comment by RayTsui** [comment]
Hi guys, 

I repeated your instructions to overcome the posted errors using commands as follows:
"spark-shell --master yarn --jars graphframes-0.5.0-spark2.1-s_2.11.jar scala-logging-slf4j_2.10-2.1.2.jar scala-logging-api_2.10-2.1.2.jar"

And then I execute the example graphframe code
"import org.graphframes._
// Create a Vertex DataFrame with unique ID column "id"
val v = sqlContext.createDataFrame(List(
  ("a", "Alice", 34),
  ("b", "Bob", 36),
  ("c", "Charlie", 30)
)).toDF("id", "name", "age")
// Create an Edge DataFrame with "src" and "dst" columns
val e = sqlContext.createDataFrame(List(
  ("a", "b", "friend"),
  ("b", "c", "follow"),
  ("c", "b", "follow")
)).toDF("src", "dst", "relationship")
// Create a GraphFrame
import org.graphframes.GraphFrame
val g = GraphFrame(v, e)"

it still gave me the following error:

"error: bad symbolic reference. A signature in Logging.class refers to term scalalogging
in package com.typesafe which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling Logging.class.
<console>:27: error: bad symbolic reference. A signature in Logging.class refers to term slf4j
in value com.typesafe.scalalogging which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling Logging.class.
       val g = GraphFrame(v, e)"

Since this issue has been closed, so if anyone has the solution, please figure it out. Thanks a lot.

**Comment by nomiero** [comment]
Same as @jnmiller Unable to use 0.6.0 with Scala 2.11, Spark 2.3.2, sbt 1.2.7
Tried adding 
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-API" % "2.1.2"
And that didn't help 
Any pointers or clues ?

**Comment by jnmiller** [comment]
Followup -- I can get 0.6.0 to run on EMR (emr-5.19.0, Spark 2.3.2) by just providing `--packages graphframes:graphframes:0.6.0-spark2.3-s_2.11` to `spark-submit` along with my jar that has been compiled with sbt package and `libraryDependencies += "graphframes" % "graphframes" % "0.6.0-spark2.3-s_2.11"`. 

**However, I cannot get my code to run on my local machine** (also Spark 2.3.2) for testing using `spark-submit`. Here is some selected output:

```
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-28b5c884-862c-4368-a3be-e3b793fe249d;1.0
	confs: [default]
	found graphframes#graphframes;0.6.0-spark2.3-s_2.11 in spark-list
	found com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 in spark-list
	found com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 in spark-list
	found org.scala-lang#scala-reflect;2.11.0 in spark-list
	[2.11.0] org.scala-lang#scala-reflect;2.11.0
	found org.slf4j#slf4j-api;1.7.7 in local-m2-cache
:: resolution report :: resolve 208ms :: artifacts dl 10ms
	:: modules in use:
	com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 from spark-list in [default]
	com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 from spark-list in [default]
	graphframes#graphframes;0.6.0-spark2.3-s_2.11 from spark-list in [default]
	org.scala-lang#scala-reflect;2.11.0 from spark-list in [default]
	org.slf4j#slf4j-api;1.7.7 from local-m2-cache in [default]
... [SNIP] ...
2019-01-04 14:08:43 INFO  SparkContext:54 - Added JAR file:///Users/jared/.ivy2/jars/com.typesafe.scala-logging_scala-logging-api_2.11-2.1.2.jar at spark://<mylaptop>:59446/jars/com.typesafe.scala-logging_scala-logging-api_2.11-2.1.2.jar with timestamp 1546639723278
2019-01-04 14:08:43 INFO  SparkContext:54 - Added JAR file:///Users/jared/.ivy2/jars/com.typesafe.scala-logging_scala-logging-slf4j_2.11-2.1.2.jar at spark://<mylaptop>:59446/jars/com.typesafe.scala-logging_scala-logging-slf4j_2.11-2.1.2.jar with timestamp 1546639723279
2019-01-04 14:08:43 INFO  SparkContext:54 - Added JAR file:///Users/jared/.ivy2/jars/org.scala-lang_scala-reflect-2.11.0.jar at spark://<mylaptop>:59446/jars/org.scala-lang_scala-reflect-2.11.0.jar with timestamp 1546639723279
2019-01-04 14:08:43 INFO  SparkContext:54 - Added JAR file:///Users/jared/.ivy2/jars/org.slf4j_slf4j-api-1.7.7.jar at spark://<mylaptop>:59446/jars/org.slf4j_slf4j-api-1.7.7.jar with timestamp 1546639723279
2019-01-04 14:08:43 INFO  SparkContext:54 - Added JAR file:///Users/jared/.ivy2/jars/graphframes_graphframes-0.6.0-spark2.3-s_2.11.jar at spark://<mylaptop>:59446/jars/graphframes_graphframes-0.6.0-spark2.3-s_2.11.jar with timestamp 1546639723279
...[SNIP]...
Exception in thread "main" java.lang.NoClassDefFoundError: com/typesafe/scalalogging/slf4j/LazyLogging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
....
```

SBT setup:

```
scalaVersion := "2.11.12"

libraryDependencies += "org.scalatest" % "scalatest_2.11" % "3.0.5" % "test"

libraryDependencies += "org.apache.spark" %% "spark-core" % "2.3.2"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.3.2"
libraryDependencies += "org.apache.spark" %% "spark-graphx" % "2.3.2"

resolvers += "Spark Packages Repo" at "http://dl.bintray.com/spark-packages/maven"
libraryDependencies += "graphframes" % "graphframes" % "0.6.0-spark2.3-s_2.11"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.1.2"
libraryDependencies += "com.typesafe.scala-logging" %% "scala-logging-api" % "2.1.2"
```

Any ideas for how I can get this running locally? The jars all seem to be there with the correct versions.

**Comment by jnmiller** [comment]
Finally!  I was able to solve the `NoClassDefFoundError` when running my tests locally by putting the scala-logging jars on the driver classpath using the following command (replace the given part of the path for your machine):

```
spark-submit --master local[*] --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11 --driver-class-path /<YOUR_PATH_HERE>/.ivy2/jars/com.typesafe.scala-logging_scala-logging-api_2.11-2.1.2.jar:/<YOUR_PATH_HERE>/.ivy2/jars/com.typesafe.scala-logging_scala-logging-slf4j_2.11-2.1.2.jar  <YOUR_JAR_HERE>.jar 
```

@nomiero

**Comment by ViPet** [comment]
> Finally! I was able to solve the `NoClassDefFoundError` when running my tests locally by putting the scala-logging jars on the driver classpath using the following command (replace the given part of the path for your machine):
> 
> ```
> spark-submit --master local[*] --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11 --driver-class-path /<YOUR_PATH_HERE>/.ivy2/jars/com.typesafe.scala-logging_scala-logging-api_2.11-2.1.2.jar:/<YOUR_PATH_HERE>/.ivy2/jars/com.typesafe.scala-logging_scala-logging-slf4j_2.11-2.1.2.jar  <YOUR_JAR_HERE>.jar 
> ```
> @nomiero

I've had this problem for a few days now, and I solved it just today. In my case, the problem was that graphframes.*.jar was inside the jars folder (in $SPARK_HOME). Even passing all the jars manually with -jars was not successfull. Removing that jar fixed it allowing me to run the program by just including the library with the -packages. Could you take a look at it? just out of curiosity.

**Comment by SemyonSinchenko** [comment]
> Scala 2.10.4 with Spark 1.5.0-cdh5.5.2

It is very old. I'm closing it now, feel free to re-open if the problem is present in the latest version of graphframes.
