### ISSUE TITLE
Update graphframes.github.io for v0.3.0

### ISSUE THREAD

**Issue by mengxr** [graphframes/graphframes#142]
I tried to update graphframes.github.io but got this error from `PRODUCTION=1 jekyll build`:

~~~
# Sphinx version: 1.2.3
# Python version: 2.7.9
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Loaded extensions:
#   underscores from /Users/meng/src/graphframes/python/docs/underscores.pyc
#   epytext from /Users/meng/src/graphframes/python/docs/epytext.pyc
#   sphinx.ext.autodoc from /Users/meng/anaconda/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
#   sphinx.ext.viewcode from /Users/meng/anaconda/lib/python2.7/site-packages/sphinx/ext/viewcode.pyc
#   sphinx.ext.oldcmarkup from /Users/meng/anaconda/lib/python2.7/site-packages/sphinx/ext/oldcmarkup.pyc
Traceback (most recent call last):
  File "/Users/meng/anaconda/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Users/meng/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 229, in build
    self.emit('build-finished', None)
  File "/Users/meng/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 408, in emit
    results.append(callback(self, *args))
  File "/Users/meng/src/graphframes/python/docs/underscores.py", line 63, in move_private_folders
    shutil.move(join(item), join(item[1:]))
  File "/Users/meng/anaconda/lib/python2.7/shutil.py", line 292, in move
    raise Error, "Destination path '%s' already exists" % real_dst
Error: Destination path '/Users/meng/src/graphframes/python/docs/_build/html/modules/_modules' already exists
~~~

cc: @thunterdb

**Comment by mengxr** [comment]
The doc site was updated.
