### ISSUE TITLE
connectedComponents() is broken in 0.3: "Checkpoint directory is not set. Please set it first using sc.setCheckpointDir()."

### ISSUE THREAD

**Issue by nchammas** [graphframes/graphframes#144]
For a minimal repro, look at [this example](https://github.com/graphframes/graphframes/issues/116#issuecomment-255875572). The code is the same, but the output in GraphFrames 0.3 is:

```
Traceback (most recent call last):
  File ".../graphframes-test.py", line 8, in <module>
    result = g.connectedComponents()
  File ".../.ivy2/jars/graphframes_graphframes-0.3.0-spark2.0-s_2.11.jar/graphframes/graphframe.py", line 228, in connectedComponents
  File "/usr/local/Cellar/apache-spark/2.0.2/libexec/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/local/Cellar/apache-spark/2.0.2/libexec/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/local/Cellar/apache-spark/2.0.2/libexec/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o59.run.
: java.io.IOException: Checkpoint directory is not set. Please set it first using sc.setCheckpointDir().
	at org.graphframes.lib.ConnectedComponents$$anonfun$2.apply(ConnectedComponents.scala:280)
	at org.graphframes.lib.ConnectedComponents$$anonfun$2.apply(ConnectedComponents.scala:280)
	at scala.Option.getOrElse(Option.scala:121)
	at org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:279)
	at org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nchammas** [comment]
I suppose it's not fair to call this "broken". It may just be an intentional API change.

If that's the case then I would ask: Shouldn't this be called out in the docs--that you need to set a checkpoint directory before calling `connectedComponents()`? (And why wasn't this required in GraphFrames 0.2?)

**Comment by jkbradley** [comment]
It's documented in the class docs, but it looks like those weren't pushed to github.io.  I'll see about doing that (or feel free to send a PR for the doc site).

Honestly, we were getting enough bug reports about scaling that I think it's better to force users to use checkpointing by default.

**Comment by felixcheung** [comment]
@jkbradley I could open a PR on .io side - I have a couple of PRs (including some updating doc) if you could help review please? 😄

**Comment by felixcheung** [comment]
it may be talked about in class doc, in `setCheckpointInterval`, but there isn't a reference to `setCheckpointDir` in the doc for the `run` method?

I think `setCheckpointInterval` might be easily overlooked.

**Comment by jkbradley** [comment]
Mentioning it in setCheckpointInterval sounds good to me

**Comment by nchammas** [comment]
@felixcheung @jkbradley - Do we still need this issue?

**Comment by felixcheung** [comment]
I'm all for more clarity in documentation
