### ISSUE TITLE
GraphFrames 0.3.0 java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by michaelqiu94** [graphframes/graphframes#146]
I am using GraphFrames 0.3.0, and whenever I try to load/create any kind of GraphFrame, I get this error:

Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I even tried loading an example GraphFrame from import org.graphframes.examples, and same result.

**Comment by hapiri** [comment]
I got this same!Windows and Mac....

**Comment by felixcheung** [comment]
how do you start/run the example? could you include your environment and commandline you use?

**Comment by michaelqiu94** [comment]
I am running this through maven. I am using Spark 2.0.2 and GraphFrames 0.3.0 for Spark 2.0 and Scala 2.11. This error occurs when I do a simple command to create a GraphFrame:

val g = GraphFrame(v, e)

This also occurs when I run this:

import org.graphframes.examples
val g: GraphFrame = examples.Graphs.friends

**Comment by michaelqiu94** [comment]
Issue solved. I was using a different version of scala logging than the one GraphFrames uses, and that is what caused the IncompatibleClassChangeError.

**Comment by strycker** [comment]
@michaelqiu94 , can you provide any details on what scala logging libraries / versions you were using that were causing this error?  I am running into the same bug myself, but I cannot seem to track down which libraries are incompatible
