### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/graphx/VertexRDD when trying examples

### ISSUE THREAD

**Issue by sbromberger** [graphframes/graphframes#147]
build.sbt:
```
...
scalaVersion := "2.11.8"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.0.2"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.0.2"
libraryDependencies += "graphframes" % "graphframes" % "0.3.0-spark2.0-s_2.11"
resolvers += "Spark Packages Repo" at "http://dl.bintray.com/spark-packages/maven"
```

code:
```
package com.bromberger.graphframeutils

import org.apache.spark.SparkConf
import org.apache.spark.sql._
import org.graphframes._
import org.graphframes.examples

object GraphFrameHelper {
   def main(args: Array[String]): Unit = {
     val conf = new SparkConf().setAppName("test").setMaster("local[*]")
     val spark = SparkSession.builder().config(conf).getOrCreate()
     val g: GraphFrame = examples.Graphs.friends
   }
}
```

Result:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/graphx/VertexRDD
	at org.graphframes.examples.Graphs.friends(Graphs.scala:85)
	at com.bromberger.graphframeutils.GraphFrameHelper$.main(GraphFrameHelper.scala:12)
	at com.bromberger.graphframeutils.GraphFrameHelper.main(GraphFrameHelper.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.graphx.VertexRDD
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 8 more
```

What am I missing? Does GraphFrames require GraphX?

(updated with simpler example taken from http://graphframes.github.io/user-guide.html)

**Comment by felixcheung** [comment]
Yes it does, could you try adding `spark-graphx` as libraryDependencies?

**Comment by sbromberger** [comment]
That worked; thank you. A couple of suggestions:

1) This dependency should be listed prominently in the documentation. (I'm happy to provide a PR for this if it would help. There are a few other things, like getting `sqlContext`, that are not adequately explained.)
2) A check that results in compile-time (vs run-time) error would be better.

**Comment by felixcheung** [comment]
Sure - more documentation is a good idea. I think generally you start from Spark to load graphframe as a package though, as documented here: https://github.com/graphframes/graphframes/blob/master/docs/quick-start.md

**Comment by sbromberger** [comment]
That's fine if you're testing in the REPL but creating a project is a different process and one that doesn't seem to be well-documented:

1) dependencies include graphx
2) a SparkSession needs to be created
3) a SQLContext needs to be created if you're creating your own dataframes for a graph

It's interesting to me that dataframes isn't an explicit dependency but graphx is. Why is that?

**Comment by felixcheung** [comment]
The use of SQLContext instead of SparkSession could be an issue with Spark 2 - this would be good to investigate.

Since you have `spark-sql` on the `libraryDependencies` - that satisfies the build requirement for dataFrame and SQLContext/SparkSession.

Thank you for bringing up these points - I don't control this repo but I think they would appreciate your input and PRs for fixes.

**Comment by thunterdb** [comment]
@sbromberger thank you for bringing up these documentation issues. If you have some suggestions for the documentation, we will gladly take accept some pull requests.

regarding the compile time error, I agree that this is unexpected. I will check the maintainers of `spark-packages-sbt` to see if we can do something on this side.

**Comment by SemyonSinchenko** [comment]
We removed `spark-packages-sbt` in #485 
Feel free to re-open if the issue is still present in the latest version.
