### ISSUE TITLE
Getting ImportError while trying to use graphframe in pyspark shell in EMR

### ISSUE THREAD

**Issue by abhishek-ch** [graphframes/graphframes#172]
I am simply trying to load GraphFrame in Pyspark Shell in aws EMR but I am always getting ImportError No Module named graphframes

I am using Spark 2.1.0

```
from graphframes import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named graphframes
```

I am using following command to load -
`pyspark --packages graphframes:graphframes:0.2.0-spark2.0-s_2.11`

The Above issue doesn't replicate when using spark-submit command with python script.
The same issue doesn't replicate with Spark-shell.

I am using Python - 2.7.1

Following is the pyspark shell logs while loading dataframe library -

```
Python 2.7.12 (default, Sep  1 2016, 22:14:00) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Ivy Default Cache set to: /home/hadoop/.ivy2/cache
The jars for the packages stored in: /home/hadoop/.ivy2/jars
:: loading settings :: url = jar:file:/usr/lib/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
	found graphframes#graphframes;0.2.0-spark2.0-s_2.11 in spark-packages
	found com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 in central
	found com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 in central
	found org.scala-lang#scala-reflect;2.11.0 in central
	found org.slf4j#slf4j-api;1.7.7 in central
:: resolution report :: resolve 312ms :: artifacts dl 10ms
	:: modules in use:
	com.typesafe.scala-logging#scala-logging-api_2.11;2.1.2 from central in [default]
	com.typesafe.scala-logging#scala-logging-slf4j_2.11;2.1.2 from central in [default]
	graphframes#graphframes;0.2.0-spark2.0-s_2.11 from spark-packages in [default]
	org.scala-lang#scala-reflect;2.11.0 from central in [default]
	org.slf4j#slf4j-api;1.7.7 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   5   |   0   |   0   |   0   ||   5   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent
	confs: [default]
	0 artifacts copied, 5 already retrieved (0kB/10ms)
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
17/02/12 17:37:53 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
17/02/12 17:37:55 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
17/02/12 17:37:58 WARN Client: Same path resource file:/home/hadoop/.ivy2/jars/graphframes_graphframes-0.2.0-spark2.0-s_2.11.jar added multiple times to distributed cache.
17/02/12 17:37:58 WARN Client: Same path resource file:/home/hadoop/.ivy2/jars/com.typesafe.scala-logging_scala-logging-api_2.11-2.1.2.jar added multiple times to distributed cache.
17/02/12 17:37:58 WARN Client: Same path resource file:/home/hadoop/.ivy2/jars/com.typesafe.scala-logging_scala-logging-slf4j_2.11-2.1.2.jar added multiple times to distributed cache.
17/02/12 17:37:58 WARN Client: Same path resource file:/home/hadoop/.ivy2/jars/org.scala-lang_scala-reflect-2.11.0.jar added multiple times to distributed cache.
17/02/12 17:37:58 WARN Client: Same path resource file:/home/hadoop/.ivy2/jars/org.slf4j_slf4j-api-1.7.7.jar added multiple times to distributed cache.
```

**Comment by hughchristensen** [comment]
Sounds like a similar error to the one we have been getting. We have been discussing with AWS. 

I understand that you are trying to import "graphframe" module into your PySpark session. I was able to reproduce your issue on my cluster running EMR 5.2.0.

I extracted the JAR contents and was able to import the module when I started the PySpark session from within the "graphframes" directory (because it has the "__init__.py" file). That said, PySpark was able to import the package that is within the current working directory without having that package in my PYTHONPATH, as a local import but couldn't import when I started the session from anywhere else. From anywhere else, I’ll need my PYTHONPATH variable to point to it.

Please follow below the steps to import the module -

1. Download "0.3.0-spark2.0-s_2.11" from http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.3.0-spark2.0-s_2.11/graphframes-0.3.0-spark2.0-s_2.11.jar

2. extract the JAR contents - jar xf graphframes_graphframes-0.3.0-spark2.0-s_2.11.jar

3. Navigate to "graphframe" directory and zip the contents inside of it.
zip graphframes.zip -r *

4. copy the zipped file to your home - cp graphframes.zip /home/hadoop/

5. Set environment variable.

ADD these environment variables to your "/etc/spark/conf/spark-env.sh" file. PySpark will use these variables.

export PYSPARK_PYTHON=python34
export PYTHONPATH=$PYTHONPATH:/home/hadoop/graphframes.zip:.

6. pyspark --packages graphframes:graphframes:0.3.0-spark2.0-s_2.11

7. Make sure the "graphframes.zip" is in the PYTHONPATH

>>> import sys
>>> print(sys.path)

8. from graphframe import *

I was then able to complete quick start guide of "graphframe" available at https://graphframes.github.io/quick-start.html

**Comment by abckaspersky** [comment]
Thanks for the same :-)

**Comment by sandys** [comment]
this works brilliantly. Is there a plan to package/include the correct version of graphframes ? because I'm getting this exact same error on IBM, Google Cloud and AWS clusters!

**Comment by felixcheung** [comment]
The issue is with `--packages` command not making the python package available or loadable from the Spark client/driver. The above workaround would work fine. It might be slightly easier to have a graphframe directory as described here: http://stackoverflow.com/questions/36397136/importing-pyspark-packages

**Comment by hughchristensen** [comment]
Since this is not interactive job, you can run your python script using an EMR step that would run spark-submit. 

An example AWS CLI command to submit a spark step (which you can translate the param's to boto API of run_job_flow() or add_job_flow_steps())

aws emr add-steps --cluster-id j-N8QWCN5C0XCL --steps Type=spark,Name=SparkPyscriptRun,Args=[--packages,graphframes:graphframes:0.3.0-spark2.0-s_2.11,--deploy-mode,cluster,--master,yarn,s3://mannem.ne/script.py],ActionOnFailure=CONTINUE

Where s3://mannem.ne/script.py is the python script which can import graphframes and work on it. Note that you can provide the  "--packages graphframes:graphframes:0.3.0-spark2.0-s_2.11" as arguments to the spark-submit , so that this package will be automatically downloaded on the fly. 

The step would eventually run a command like : 

spark-submit --packages graphframes:graphframes:0.3.0-spark2.0-s_2.11 --deploy-mode cluster --master yarn /home/hadoop/script.py

script.py
-------------------------------------------------
from __future__ import print_function
import sys
import graphframes
from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext

conf = SparkConf().setAppName("Log Analyzer")
sc = SparkContext(conf=conf)
sqlContext = SQLContext(sc)

# Create a Vertex DataFrame with unique ID column "id"
v = sqlContext.createDataFrame([
  ("a", "Alice", 34),
  ("b", "Bob", 36),
  ("c", "Charlie", 30),
], ["id", "name", "age"])
# Create an Edge DataFrame with "src" and "dst" columns
e = sqlContext.createDataFrame([
  ("a", "b", "friend"),
  ("b", "c", "follow"),
  ("c", "b", "follow"),
], ["src", "dst", "relationship"])
# Create a GraphFrame
from graphframes import *
g = GraphFrame(v, e)

# Query: Get in-degree of each vertex.
g.inDegrees.show()
-------------------------------------------------

Hope this helps.

**Comment by sandys** [comment]
hi hugh
we were also running our analysis in an interactive mode pyspark shell.

what should we do in this case? we spawn clusters and shut them down (to
save costs).  it's fairly tricky for our data scientists to do the work
around above.

any suggestions on how to package this in a way that it works seamlessly?
we are happy to host our own packages in case you are not sure you want to
do this in the main repo

**Comment by AbdealiJK** [comment]
I have the same concern as @sandys

**Comment by felixcheung** [comment]
I think the main step is the `--packages` parameter? is this not going to work with on-demand cluster?

**Comment by caseyvu** [comment]
@hughchristensen : great guide! just 1 issue though, in step 3 where we zip the graphframes folder, I realized that I should zip the whole folder, like so:
(from the parent folder of graphframes)
zip -r graphframes.zip graphframes

**Comment by sandys** [comment]
hi guys,
has there been any progress on this issue ? There are different modes in which people run pyspark (zeppelin in cluster mode, pyspark shell, spark-submit). It would be really great to have a way where graphframes is seamlessly available through commandline.

We have been doing a workaround of spark.sparkContext.addPyFile(os.path.expanduser(GRAPH_FRAME_JAR_PATH)) - but this then works differently on cluster mode vs local mode. We are having to do a lot of hackery just for graphframes.

**Comment by felixcheung** [comment]
I think this is an issue with how pyspark shell handles Spark packages (`--packages`).
Probably best to follow in the Spark project. Please open a JIRA https://issues.apache.org/jira/issues/?jql=project%3DSpark and feel free to add me to it.

**Comment by sandys** [comment]
@felixcheung  thanks for replying! In your experience does Zeppelin-pyspark (or other altenatives to pyspark shell) avoid these issues ? Or does this happen with every pyspark related tool.

I'm kind of looking for something that will let me move ahead with this for the time being.

**Comment by sandys** [comment]
@felixcheung one more question - is there a way to copy the graphframes library jar + python code into the pyspark installation such that i dont even have to muck around with the --jars or --files or anything. just have it seamlessly available ?
If this is possible, i will setup my spark install script to do this (on my entire cluster), rather than depend on commandline. this will be a big help !

**Comment by felixcheung** [comment]
try `spark.submit.pyFiles`? http://spark.apache.org/docs/latest/configuration.html#runtime-environment

**Comment by sandys** [comment]
hi felix
thanks for replying. I thought of this - but i didnt know how to handle the
situations where im running the code in local mode versus cluster mode.
I have done something else now - i have taken the jar file and dropped in
inside /usr/lib/spark/jars and then i created a wheel file from your python
code and installed it on the same machine.
now graphframes works fine.
I wonder if there is way to package graphframes in split form - the jar and
the wheel separately so that the installation is seamless. I dont mine
running two different commands.

**Comment by brifordwylie** [comment]
I've created a new issue #238 asking for the creation of a PyPI package.

**Comment by felixcheung** [comment]
hi! yes I think as a package on PyPI would be easier. Think we would need some way to download the jar on the fly similar to how Pyspark does it

**Comment by sandys** [comment]
I would recommend packaging the jar file inside the pypi package. In a lot
of places, package downloads are audited and heavily restricted. Especially
for things like data analysis (which touches sensitive data).

The ideal way to do this is for the build step for the python package to
create a self contained wheel file which also carries the jar.

Also want to mention that this will probably need some patching in
Zeppelin. When I made this work, I saw some conflicts between the scala
reflect packages in Zeppelin, so had to move the jars in a different
directory.

Zeppelin should be able to pick up the jar file from the graphframes python
package.

On 17-Sep-2017 08:35, "Felix Cheung" <notifications@github.com> wrote:

hi! yes I think as a package on PyPI would be easier. Think we would need
some way to download the jar on the fly similar to how Pyspark does it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/graphframes/graphframes/issues/172#issuecomment-330011055>,
or mute the thread

**Comment by jklukas** [comment]
Here's a workaround that seems to get the right paths for `--packages` entries available to an EMR pyspark session:

```python
import sys
pyfiles = str(sc.getConf().get(u'spark.submit.pyFiles')).split(',')
sys.path.extend(pyfiles)
```

**Comment by TamouzeAssi** [comment]
Hi @hughchristensen  doing your steps above i get the following:

```
Traceback (most recent call last):
  File "C:/Users/user/Desktop/utils.py", line 49, in <module>
    g = GraphFrame(v, e)
  File "C:\Users\user\Desktop\graphframes\graphframe.py", line 68, in __init__
    self._jvm_gf_api = _java_api(self._sc)
  File "C:\Users\user\Desktop\graphframes\graphframe.py", line 41, in _java_api
    return jsc._jvm.Thread.currentThread().getContextClassLoader().loadClass(jav
aClassName) \
  File "C:\spark-2.3.0-bin-hadoop2.7\python\lib\py4j-0.10.6-src.zip\py4j\java_ga
teway.py", line 1160, in __call__
  File "C:\spark-2.3.0-bin-hadoop2.7\python\lib\pyspark.zip\pyspark\sql\utils.py
", line 63, in deco

  File "C:\spark-2.3.0-bin-hadoop2.7\python\lib\py4j-0.10.6-src.zip\py4j\protoco
l.py", line 320, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o91.loadClass.
: java.lang.ClassNotFoundException: org.graphframes.GraphFramePythonAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:745)
```

By the way, i set the variables as follows:
export PYSPARK_PYTHON=python34
export PYTHONPATH=$PYTHONPATH:/C:/graphframes.zip:

can you please help?

**Comment by ShuklaPranav** [comment]
Hi

> Sounds like a similar error to the one we have been getting. We have been discussing with AWS.
> 
> I understand that you are trying to import "graphframe" module into your PySpark session. I was able to reproduce your issue on my cluster running EMR 5.2.0.
> 
> I extracted the JAR contents and was able to import the module when I started the PySpark session from within the "graphframes" directory (because it has the "**init**.py" file). That said, PySpark was able to import the package that is within the current working directory without having that package in my PYTHONPATH, as a local import but couldn't import when I started the session from anywhere else. From anywhere else, I’ll need my PYTHONPATH variable to point to it.
> 
> Please follow below the steps to import the module -
> 
> 1. Download "0.3.0-spark2.0-s_2.11" from http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.3.0-spark2.0-s_2.11/graphframes-0.3.0-spark2.0-s_2.11.jar
> 2. extract the JAR contents - jar xf graphframes_graphframes-0.3.0-spark2.0-s_2.11.jar
> 3. Navigate to "graphframe" directory and zip the contents inside of it.
>    zip graphframes.zip -r *
> 4. copy the zipped file to your home - cp graphframes.zip /home/hadoop/
> 5. Set environment variable.
> 
> ADD these environment variables to your "/etc/spark/conf/spark-env.sh" file. PySpark will use these variables.
> 
> export PYSPARK_PYTHON=python34
> export PYTHONPATH=$PYTHONPATH:/home/hadoop/graphframes.zip:.
> 
> 1. pyspark --packages graphframes:graphframes:0.3.0-spark2.0-s_2.11
> 2. Make sure the "graphframes.zip" is in the PYTHONPATH
> 
> > > > import sys
> > > > print(sys.path)
> 
> 1. from graphframe import *
> 
> I was then able to complete quick start guide of "graphframe" available at https://graphframes.github.io/quick-start.html

Hi I have tried this on aws emr cluster  and followed the exact process mentioned above but when I import then I get the error
No module named 'graphframes.lib' 
Dou you have any idea why is this so.

**Comment by MohammadHeydari** [comment]
when i run 
```
from graphframes import *
g = GraphFrame(v, e)
```
i face with these errors: 
```
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-24-0b123461b580> in <module>()
      1 from graphframes import *
----> 2 g = GraphFrame(v, e)
```
and also 

```
/usr/local/lib/python3.6/dist-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o210.loadClass.
: java.lang.ClassNotFoundException: org.graphframes.GraphFramePythonAPI
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by TejalPatted** [comment]
I was facing the same issues and below steps helped me resolve it on pyspark-shell and Jupiter notebook.  
Pyspark Shell -
1. Download and extract the jar as mentioned in the reply by @hughchristensen 
2. Set environment variable to `export PYTHONPATH=$PYTHONPATH:/home/user/.ivy2/jars:.` By default the graphFrames was downloaded in /home/user/.ivy2/jars path
3. Start pyspark with `pyspark --packages graphframes:graphframes:0.6.0-spark2.2-s_2.11 --jars graphframes-0.6.0-spark2.2-s_2.11.jar`

**Note:** Make sure to download the graph frames version compatible with your Pyspark version from [Graphframes download path](http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/)

Once I completed above steps, I was able to import and use graphFrames in pyspark shell but facd below error in Jupiter notebook -
`Py4JJavaError: An error occurred while calling o210.loadClass.
: java.lang.ClassNotFoundException: org.graphframes.GraphFramePythonAPI
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:834)` 

Jupyter notebook -
1. Once the steps under pyspark-shell section are completed add `export PYSPARK_SUBMIT_ARGS="--packages graphframes:graphframes:0.6.0-spark2.2-s_2.11 pyspark-shell"` to environment variables

**Comment by mohdwasim** [comment]
Getting Forbidden Error : http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/




**C:\Users\SUPER\Downloads\splink_demos-master\splink_demos-master>pyspark --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11**
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
[I 14:24:47.882 NotebookApp] Serving notebooks from local directory: C:\Users\SUPER\Downloads\splink_demos-master\splink_demos-master
[I 14:24:47.882 NotebookApp] The Jupyter Notebook is running at:
[I 14:24:47.882 NotebookApp] http://localhost:8888/?token=ee4d1e5e3012657192f66cc5fc3d279825a1c5c764541207
[I 14:24:47.882 NotebookApp]  or http://127.0.0.1:8888/?token=ee4d1e5e3012657192f66cc5fc3d279825a1c5c764541207
[I 14:24:47.882 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:24:47.980 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/SUPER/AppData/Roaming/jupyter/runtime/nbserver-10884-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ee4d1e5e3012657192f66cc5fc3d279825a1c5c764541207
     or http://127.0.0.1:8888/?token=ee4d1e5e3012657192f66cc5fc3d279825a1c5c764541207
[W 14:24:48.477 NotebookApp] 404 GET /api/kernels/29e494b3-4069-4fed-bc53-99447150e6d8/channels?session_id=16cbab58f2444fe9995471b816f80885 (::1): Kernel does not exist: 29e494b3-4069-4fed-bc53-99447150e6d8
[W 14:24:48.495 NotebookApp] 404 GET /api/kernels/29e494b3-4069-4fed-bc53-99447150e6d8/channels?session_id=16cbab58f2444fe9995471b816f80885 (::1) 19.03ms referer=None
[W 14:24:52.501 NotebookApp] Replacing stale connection: 29e494b3-4069-4fed-bc53-99447150e6d8:16cbab58f2444fe9995471b816f80885
[I 14:24:54.004 NotebookApp] Kernel started: eea4fc4d-6e9b-44b9-bbe2-64005874d6de
:: loading settings :: url = jar:file:/C:/spark-3.1.1-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: C:\Users\SUPER\.ivy2\cache
The jars for the packages stored in: C:\Users\SUPER\.ivy2\jars
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-43846a9a-2631-4b6a-a01c-b565aae6cc63;1.0
        confs: [default]
:: resolution report :: resolve 9008ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: graphframes#graphframes;0.6.0-spark2.3-s_2.11

        ==== local-m2-cache: tried

          file:/C:/Users/SUPER/.m2/repository/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          file:/C:/Users/SUPER/.m2/repository/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

        ==== local-ivy-cache: tried

          C:\Users\SUPER\.ivy2\local\graphframes\graphframes\0.6.0-spark2.3-s_2.11\ivys\ivy.xml

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          C:\Users\SUPER\.ivy2\local\graphframes\graphframes\0.6.0-spark2.3-s_2.11\jars\graphframes.jar

        ==== central: tried

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

        ==== spark-packages: tried

          https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          https://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: graphframes#graphframes;0.6.0-spark2.3-s_2.11: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.6.0-spark2.3-s_2.11: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1420)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[IPKernelApp] WARNING | Unknown error in handling PYTHONSTARTUP file C:\spark-3.1.1-bin-hadoop2.7\python\pyspark\shell.py:

**Comment by ashish-3916** [comment]
how can we do if we are using google collab only?

**Comment by chandnim493** [comment]
can someone please help with the steps to work with the property graph model and AWS EMR?

**Comment by chandnim493** [comment]
can someone help me with mapping the property graph model to Hadoop

**Comment by senthil-bungee** [comment]
Where can I find whl package for 0.8.2-spark3.1-s_2.12?

**Comment by SemyonSinchenko** [comment]
The issue is outdated, I'm closing it now. Feel free to re-open if you face it with the latest versions of spark and graphframes.

P.S. We are going to start publishing to Maven Central, tracking issue is: #510 as well as publishing to pypi (graphframes-py). With the new release of graphframes-py, JAR will be included to the distribution.
P.P.S. @chandnim493 we are working on the support of property graphs, tracking issue is #565
