### ISSUE TITLE
Checkpoint to s3 not working

### ISSUE THREAD

**Issue by mavencode01** [graphframes/graphframes#175]
I'm trying to deploy my job to aws EMR and using s3 as my checkpoint dir but I'm getting an exception using s3. 

	java.lang.IllegalArgumentException: Wrong FS: s3://spark-jobs/supercluster-checkpoint/f9d90be3-bb3e-4a7f-8009-37bb4d697f67/connected-components-e7bf178a/2, expected: hdfs://ip-172-18-13-6.ec2.internal:8020
		at org.apache.hadoop.fs.FileSystem.checkPath(FileSystem.java:652)
		at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:194)
		at org.apache.hadoop.hdfs.DistributedFileSystem.access$000(DistributedFileSystem.java:106)
		at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:707)
		at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:703)
		at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
		at org.apache.hadoop.hdfs.DistributedFileSystem.delete(DistributedFileSystem.java:703)
		at org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:340)
		at org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:139)
		at com.sonatype.aname.sparkjob.SuperClusterV2$.main(SuperClusterV2.scala:87)
		at com.sonatype.aname.sparkjob.SuperClusterV2.main(SuperClusterV2.scala)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:637)

Is it possible to use s3 as Checkpoint directory ?

**Comment by felixcheung** [comment]
It should work with this commit https://github.com/graphframes/graphframes/commit/5cfc0276d7e874c65c2be0acb1c9787e0ed27b26

Would you be able to run against the latest source of GraphFrame?

**Comment by mavencode01** [comment]
Is that published yet to the spark packages ?

**Comment by felixcheung** [comment]
Not yet, AFAIK.

**Comment by mavencode01** [comment]
Thanks @felixcheung I was able to run against the latest source and it worked.
