### ISSUE TITLE
bug: ConnectedComponents: error 'Unable to infer schema for Parquet. It must be specified manually'

### ISSUE THREAD

**Issue by thomasopsomer** [graphframes/graphframes#201]
Hi,

When computing `connectedComponents`using the graphframes algorithm I get the following error:
```
File "/root/.ivy2/jars/graphframes_graphframes-0.5.0-spark2.1-s_2.11.jar/graphframes/graphframe.py", line 279, in connectedComponents
File "/usr/spark-2.1.1-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
File "/usr/spark-2.1.1-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
pyspark.sql.utils.AnalysisException: u'Unable to infer schema for Parquet. It must be specified manually.;'
```
Looking at the code, I guess this is due to saving an empty checkpoint in parquet format. Because there are similar issues with spark when trying to load empty parquet files. So maybe more a spark issue, however in the meantime, checking if the [`ee`](https://github.com/graphframes/graphframes/blob/master/src/main/scala/org/graphframes/lib/ConnectedComponents.scala#L333) dataframe is empty before saving it to parquet could help ?.

Thomas.

**Comment by felixcheung** [comment]
thanks- do you know how dataframe is empty?

**Comment by thomasopsomer** [comment]
Actually I don't. It is a guess, because of the similar issues I've seen around... Other information: the graph I'm working on is very sparse like 4M node and 3M components...

**Comment by felixcheung** [comment]
I see, I think that would be very good to have. Would you be interested in contributing a fix and test for this?

**Comment by thomasopsomer** [comment]
Yes sure, I'll see if it handling empty parquet fixes the issue and if so then submit a PR :)

**Comment by oliveratutexas** [comment]
Any update on this? I'm running into the same problem.

**Comment by Gmousse** [comment]
Hi, same problem here when using ConnectedComponents:

````
Unable to infer schema for Parquet. It must be specified manually.;
Traceback (most recent call last):
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/local/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o116.run.
: org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:189)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$8.apply(DataSource.scala:189)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.execution.datasources.DataSource.org$apache$spark$sql$execution$datasources$DataSource$$getOrInferFileFormatSchema(DataSource.scala:188)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:387)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:441)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:425)
	at org.graphframes.lib.ConnectedComponents$.org$graphframes$lib$ConnectedComponents$$run(ConnectedComponents.scala:335)
	at org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
````

**Comment by Gmousse** [comment]
After some tests, the checkpoint fail only to write on local file system (but doesn't throw errors).

Then when the ConnectedComponents try to reload the checkpoints, the checkpoint parquet is empty (without schema) and fails to load.

This issue doesn't occur when using google storage or s3 to write the checkpoint.

**Comment by felixcheung** [comment]
yes, this seems to be the case when the checkpoint results in an empty file.
In you case, do you know why it fails only for local file system? can you tell us more about the environment you are running this in?

**Comment by Gmousse** [comment]
I don't know why checkpointing is failing on local system. I m on a debian 8 instance (on google compute engine environment) with spark 2.1. I think it's environment related and m 90% sure that it's not related to your library. 

The only improvement to do could be to throw warnings (or handle the error) if the checkpoint can't be written (or loaded) and if the dataframe wasn't empty.  Like that, even if it's related to an environment issue, the user could detect the problem faster.

However, you can close the issue.

**Comment by bsplosion** [comment]
I also came across this issue, but my context was a job running on AWS Glue after upgrading to Glue 3.0.

The comments about the checkpoint file being empty lead me to the correct solution: Glue 3.0 deprecated HDFS, but existing checkpoint directory settings weren't altered so the ConnectedComponents I/O failed quietly (e.g., my setting was for "/tmp/spark-checkpoint" which wasn't writable with HDFS gone).  Setting an S3 location for the checkpoints corrected the problem.  Hope this helps some other poor soul scouring message boards!

**Comment by chaitu0599** [comment]
I am also facing the same issue when running a job on AWS Glue 3.0 

Can anyone please tell me how to set S3 location for the checkpoints for my job??

**Comment by alfredo-f** [comment]
> I also came across this issue, but my context was a job running on AWS Glue after upgrading to Glue 3.0.
> 
> The comments about the checkpoint file being empty lead me to the correct solution: Glue 3.0 deprecated HDFS, but existing checkpoint directory settings weren't altered so the ConnectedComponents I/O failed quietly (e.g., my setting was for "/tmp/spark-checkpoint" which wasn't writable with HDFS gone). Setting an S3 location for the checkpoints corrected the problem. Hope this helps some other poor soul scouring message boards!

It did, you are awesome!

**Comment by gregorysharkov** [comment]
for my a graphx alternative worked just fine:
```python
graph.connectedComponents(algorithm="graphx")
```

**Comment by katidieter** [comment]
> I had the same issue with default algo. Setting up the checkpoint dir did not work well, however using a graphx alternative worked just fine:
> 
> ```python
> graph.connectedComponents(algorithm="graphx")
> ```

I am actually running a spark magic session at Sagemaker and your suggestion would help me solves my problem. Thanks, @gregorysharkov!

**Comment by SemyonSinchenko** [comment]
@SauronShepherd Hi! It looks related to our planned refactoring of the whole checkpointing
