### ISSUE TITLE
java.lang.UnsupportedClassVersionError: com/typesafe/scalalogging/Logger : Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by RayTsui** [graphframes/graphframes#240]
When I execute the spark-shell in cluster and I input
val graphframes = GraphFrame.fromEdges(edges)
it gives me as follows:
java.lang.UnsupportedClassVersionError: com/typesafe/scalalogging/Logger : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
... 50 elided

**Comment by felixcheung** [comment]
it was suggested this can result from an older version of java - which version are you running with?

**Comment by RayTsui** [comment]
The java version on cluster is 
java version "1.7.0_60-ea"
Java(TM) SE Runtime Environment (build 1.7.0_60-ea-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Is something wrong?

**Comment by felixcheung** [comment]
could you check your classpath and scala version?
perhaps com/typesafe/scalalogging/Logger  is there and not working with your java version?

**Comment by RayTsui** [comment]
I have requested my colleagues to check the configuration in the cluster, I will post the feedback if the solution is available.

**Comment by SemyonSinchenko** [comment]
I'm closing it now because it is very old. Feel free to re-open if the issue is still present in the latest versions of graphframes and spark.
