### ISSUE TITLE
Finding Edge without a loop OR triangle

### ISSUE THREAD

**Issue by purohitsumit** [graphframes/graphframes#254]
Hi All,
I am trying to find all the occurrences of edges which are not part of any loop OR triangle. 
I used the motif expression as "(a)-[]->(b); !(b)-[]->(c); !(c)-[]->(a); !(b)-[]->(a)"
But i get Following Exception:
**Exception in thread "main" org.apache.spark.sql.AnalysisException: Except can only be performed on tables with the same number of columns, but the first table has 2 columns and the second table has 3 columns;;**

I am not sure what is wrong in this expression. I appreciate any help.

`
Exception in thread "main" org.apache.spark.sql.AnalysisException: Except can only be performed on tables with the same number of columns, but the first table has 2 columns and the second table has 3 columns;;
'Except
:- Project [a#29, b#32]
:  +- Join Inner, (__tmp-4363599943432734077#26.dst = b#32.id)
:     :- Join Inner, (__tmp-4363599943432734077#26.src = a#29.id)
:     :  :- Project [named_struct(src, src#19, dst, dst#20, time, time#21L) AS __tmp-4363599943432734077#26]
:     :  :  +- Project [_1#15 AS src#19, _2#16 AS dst#20, _3#17L AS time#21L]
:     :  :     +- SerializeFromObject [assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._1 AS _1#15, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._2 AS _2#16, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._3 AS _3#17L]
:     :  :        +- ExternalRDD [obj#14]
:     :  +- Project [named_struct(id, id#6, name, name#7) AS a#29]
:     :     +- Project [_1#3 AS id#6, _2#4 AS name#7]
:     :        +- SerializeFromObject [assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1 AS _1#3, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2 AS _2#4]
:     :           +- ExternalRDD [obj#2]
:     +- Project [named_struct(id, id#6, name, name#7) AS b#32]
:        +- Project [_1#3 AS id#6, _2#4 AS name#7]
:           +- SerializeFromObject [assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1 AS _1#3, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2 AS _2#4]
:              +- ExternalRDD [obj#2]
+- Project [a#108, b#110, c#68]
   +- Join Inner, (__tmp3640351034883199571#65.dst = c#68.id)
      :- Join Inner, (__tmp3640351034883199571#65.src = b#110.id)
      :  :- Project [a#108, b#110]
      :  :  +- Join Inner, (__tmp-4363599943432734077#26.dst = b#110.id)
      :  :     :- Join Inner, (__tmp-4363599943432734077#26.src = a#108.id)
      :  :     :  :- Project [named_struct(src, src#19, dst, dst#20, time, time#21L) AS __tmp-4363599943432734077#26]
      :  :     :  :  +- Project [_1#15 AS src#19, _2#16 AS dst#20, _3#17L AS time#21L]
      :  :     :  :     +- SerializeFromObject [assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._1 AS _1#15, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._2 AS _2#16, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._3 AS _3#17L]
      :  :     :  :        +- ExternalRDD [obj#14]
      :  :     :  +- Project [named_struct(id, id#6, name, name#7) AS a#108]
      :  :     :     +- Project [_1#3 AS id#6, _2#4 AS name#7]
      :  :     :        +- SerializeFromObject [assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1 AS _1#3, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2 AS _2#4]
      :  :     :           +- ExternalRDD [obj#2]
      :  :     +- Project [named_struct(id, id#6, name, name#7) AS b#110]
      :  :        +- Project [_1#3 AS id#6, _2#4 AS name#7]
      :  :           +- SerializeFromObject [assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1 AS _1#3, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2 AS _2#4]
      :  :              +- ExternalRDD [obj#2]
      :  +- Project [named_struct(src, src#19, dst, dst#20, time, time#21L) AS __tmp3640351034883199571#65]
      :     +- Project [_1#15 AS src#19, _2#16 AS dst#20, _3#17L AS time#21L]
      :        +- SerializeFromObject [assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._1 AS _1#15, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._2 AS _2#16, assertnotnull(input[0, scala.Tuple3, true], top level Product input object)._3 AS _3#17L]
      :           +- ExternalRDD [obj#14]
      +- Project [named_struct(id, id#6, name, name#7) AS c#68]
         +- Project [_1#3 AS id#6, _2#4 AS name#7]
            +- SerializeFromObject [assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._1 AS _1#3, assertnotnull(input[0, scala.Tuple2, true], top level Product input object)._2 AS _2#4]
               +- ExternalRDD [obj#2]
	at 
org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.failAnalysis(CheckAnalysis.scala:40)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.failAnalysis(Analyzer.scala:57)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$16.apply(CheckAnalysis.scala:308)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$16.apply(CheckAnalysis.scala:305)
	at scala.collection.immutable.List.foreach(List.scala:318)
`

**Comment by felixcheung** [comment]
Hmm, this is odd. What is your dataset? it looks like perhaps a tuple as column? Would it be possible to have a smaller set of code to reproduce this problem?

**Comment by purohitsumit** [comment]
Hi @felixcheung ,

I have created a gist with core code ,and the data.
https://gist.github.com/purohitsumit/a820a1a3af2f00347bb6343dc1fe31da

What do you mean by "looks like perhaps a tuple as column" ?

**Comment by purohitsumit** [comment]
I even used the graph in user-guide. I get the same error.
    // Vertex DataFrame
val v = sqlContext.createDataFrame(List(
  ("a", "Alice", 34),
  ("b", "Bob", 36),
  ("c", "Charlie", 30),
  ("d", "David", 29),
  ("e", "Esther", 32),
  ("f", "Fanny", 36),
  ("g", "Gabby", 60)
)).toDF("id", "name", "age")
// Edge DataFrame
val e = sqlContext.createDataFrame(List(
  ("a", "b", "friend"),
  ("b", "c", "follow"),
  ("c", "b", "follow"),
  ("f", "c", "follow"),
  ("e", "f", "follow"),
  ("e", "d", "friend"),
  ("d", "a", "friend"),
  ("a", "e", "friend")
)).toDF("src", "dst", "relationship")
// Create a GraphFrame
val g = GraphFrame(v, e)

**Comment by etherruzo** [comment]
I'm having the same error. Is there any limit in the depth of cases we can put inside the .find ?? It's giving an error when there are more than 6.

This is working:
val a: DataFrame = g.find("(a)-[]->(b);(b)-[]->(c);!(c)-[]->(b);!(b)-[]->(a);!(a)-[]->(c);!(c)-[]->(a)")


This is not working: 
val b: DataFrame = g.find("(a)-[]->(b);(b)-[]->(c);!(c)-[]->(b);!(b)-[]->(a);!(a)-[]->(c);!(c)-[]->(a);!(b)-[]->(e)")

anyone knows what's happening??

**Comment by deusxmach1na** [comment]
Any progress on this?  I get this error whenever the motif has multiple patterns and an ! (pyspark).  
```sub_graph = g.find("(a)-[e]->(b); !(b)-[r]->(c)")```

```Except can only be performed on tables with the same number of columns, but the first table has 3 columns and the second table has 5 columns;```

**Comment by felixcheung** [comment]
I'll try to reproduce it and debug within the next few days.
sorry, I have been completely swamped with work - perhaps someone else has time to investigate it too.

**Comment by strongcoder** [comment]
Thank you @felixcheung  for responding. 
Desparately looking forward to a quick resolution for this, as required by our business to build the pattern to search in graph.

**Comment by jkbradley** [comment]
This looks like an outright bug, probably introduced by Spark's Dataset.except method changing semantics.  I'm looking into it.  (Sorry it took a long time for me to see this!)

**Comment by jkbradley** [comment]
The bug is in handling of negated edges: It fails for cases in which a named vertex or edge appears in negated terms but not in non-negated terms.

*Workaround*: @purohitsumit  You can work around this bug by handling negation explicitly:
E.g., your query above `"(a)-[]->(b); !(b)-[]->(c); !(c)-[]->(a); !(b)-[]->(a)"` can be re-expressed as:
```
    // non-negated terms
    val nonnegated = g.find("(a)-[]->(b)")
      .select("a", "b")
    // negated terms
    val negated = g.find("(a)-[]->(b);(b)-[]->(c); (c)-[]->(a)")
      .select("a", "b")
    // remove motifs which are invalid b/c of negated terms
    val motifs = nonnegated.except(negated)
      .show()
```
Note the code above assumes vertices do not have self-loops.

My proposed fix is basically the same as this workaround:
* In Pattern.parse, split all patterns into 2 sets: negated and non-negated.
* Handle these 2 sets separately in GraphFrame.findSimple:
  * Find non-negated patterns.
  * Find union of negated patterns + non-negated patterns (but searching for all as non-negated).
  * Use Dataset.except (as in findIncremental) to remove negated patterns from the non-negated ones.

I believe this will handle our current DSL.  This approach may not make sense if distinct vertex labels can represent the same vertex; we may want to think about that design first.

Also, this may need to be modified if we make the DSL more expressive, such as by adding grouping.

**Comment by akkicoder** [comment]
Hi @jkbradley  @felixcheung  if time permits and if possible can this be fixed instead of a workaround. 
Also I would like to know if this workaround works in all cases. 
I have a usecase where I have a relationship graph of people connected based on attributes.
Graph details:
Vertices - People and attributes such as email, address etc.
Edges - Always starting from person and ending in the attribute vertex.

Now I want to see some connections where the persons share same email but not same address. hence any edge between those persons vertex travelling to address vertex should not even exist in the graph itself. I used motif finding negation to achieve this but received the same error as mentioned in the beginning of this issue by purohitsumit.
Please let me know if we are planning to fix this anytime soon or of you can please provide possible workaround using motif finding to achieve this usecase.

**Comment by felixcheung** [comment]
@akkicoder can you check #276 and add your feedback

**Comment by akkicoder** [comment]
Hi @jkbradley @felixcheung @thunterdb @mengxr @phi-dbq  I have 2 conceptual questions on the right way of using Motif finding

As described for my usecase the attributes are also vertex, with a property called vertex_type like email for email attribute vertex. Now my edges going from person vertex to the attribute vertex like email also have a label called hasEmail. I have following two questions:

**Question 1:**
Now if I am finding the person vetices connected on attributes email and address, and I see there are two ways of finding this same relationship :
i) Vertices filter method 
(a)-[]->(b); (c)-[]->(b) where a and c are person vertices and b is the attribute vertex. First way is to filter the vertex b on vertex_type in ('address', 'email')
ii) Edges filter method
(a)-[e1]->(b); (c)-[e2]->(b) and filter the edges e1 and e2 on label in('hasEmail,hasAddress')
Though I expect both to give the same results but somehow they gave different counts, where filtering on edges gave comparatively lesser counts. Which is the right way which ensures the output is correct?

**Question 2:**
Should (a)-[]->(b); (c)-[]->(b) and filtering the b's vertex_type in('email','address') is OK or should I instead use (a)-[]->(b); (c)-[]->(b);(a)-[]->(d); (c)-[]->(d) and then filter b.vertex_type='email' and d.vertex_type='address'. Which is the right method using in clause or separate equality to each individual value to get the accurate output?

**Comment by akkicoder** [comment]
Hi @jkbradley  @felixcheung  @thunterdb  @mengxr @phi-dbq  
Your timely response to my above question would be highly appreciated.

**Comment by akkicoder** [comment]
Hi @jkbradley @felixcheung @thunterdb @mengxr @phi-dbq 
Can you please provide the required detail. As it is a fundamental question, I hope it should not take very long to provide the response. Your response would be highly appreciated.

**Comment by pratiklodha95** [comment]
@felixcheung @jkbradley @thunterdb @mateiz @phi-dbq @akkicoder 

Has there been any updates on this ?

**Comment by SemyonSinchenko** [comment]
GraphFrames now provides an implementation of the Rocha-Thatte algorithm that finds all the cycles (loops) including triangles. With that algorithm it is simple task to find vertices that are not part of any loop.
