### ISSUE TITLE
No module named 'graphframes.lib'

### ISSUE THREAD

**Issue by wuliu1516** [graphframes/graphframes#256]
pyspark --packages graphframes:graphframes:0.5.0-spark2.1-s_2.11

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.2.1
      /_/

Using Python version 3.5.4 (default, Nov 20 2017 18:44:38)
SparkSession available as 'spark'.
>>> from graphframes.lib import AggregateMessages as AM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'graphframes.lib'
>>>

**Comment by luisbelloch** [comment]
Same problem here, trace importing example graphs

```
>>> from graphframes.examples import Graphs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/var/folders/ns/vlgjthxs7qb2gmv273wrd9bh0000gn/T/spark-05d360bc-6a2e-450f-b5b4-84c98153b341/userFiles-6e4e0f8b-909b-4b00-8bb3-c63e3f0a0053/graphframes_graphframes-0.5.0-spark2.1-s_2.11.jar/graphframes/examples/__init__.py", line 2, in <module>
  File "/private/var/folders/ns/vlgjthxs7qb2gmv273wrd9bh0000gn/T/spark-05d360bc-6a2e-450f-b5b4-84c98153b341/userFiles-6e4e0f8b-909b-4b00-8bb3-c63e3f0a0053/graphframes_graphframes-0.5.0-spark2.1-s_2.11.jar/graphframes/examples/belief_propagation.py", line 25, in <module>
ModuleNotFoundError: No module named 'graphframes.lib'
```

The exact environment I'm using can be reproduced as:

```
$ docker run -ti luisbelloch/spark pyspark --packages graphframes:graphframes:0.5.0-spark2.1-s_2.11
```

Container was created using this [Dockerfile](https://github.com/luisbelloch/data_processing_course/blob/2018.1/infra/docker/Dockerfile).

Thanks!

**Comment by artem-aliev** [comment]
Looks like sbt-spark-package exclude python lib directories, so  graphframes/lib/ is not included in the published jar.

**Comment by makmanalp** [comment]
Same here! Looks like #209 / #217 fixed this issue but a new release hasn't been made in a whole year. Is this project still being maintained?

**Comment by makmanalp** [comment]
Luckily dropping in the missing python files in the current directory and modifying code (e.g. `from aggregate_messages import AggregateMessages as AM` instead of `from graphframes.lib import ...`) seems to work okay, but kinda kills the convenience of being able to do `pyspark --packages graphframes:...`.

**Comment by SauronShepherd** [comment]
GraphFrames 0.5.0. => @rjurney, @SemyonSinchenko, I think we should close all open issues related to versions prior to 0.8.0 without hesitation. What do you think?

**Comment by SemyonSinchenko** [comment]
> GraphFrames 0.5.0. => @rjurney, @SemyonSinchenko, I think we should close all open issues related to versions prior to 0.8.0 without hesitation. What do you think?
> 

Sound good to me!
