### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/graphframes/GraphFrame

### ISSUE THREAD

**Issue by myDemoMike** [graphframes/graphframes#281]
the question is that this class I have found in my item ，and my item is  Scala programming

**Comment by myDemoMike** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: org/graphframes/GraphFrame$
        at com.test.graphx.tools.GraphBuilderImp.toGraphFrame(GraphBuilderImp.scala:139)
        at com.test.graphx.build.BuildGraph$.bkhGraphFrame$lzycompute$1(BuildGraph.scala:59)
        at com.test.graphx.build.BuildGraph$.bkhGraphFrame$1(BuildGraph.scala:59)
        at com.test.graphx.build.BuildGraph$.main(BuildGraph.scala:75)
        at com.test.graphx.build.BuildGraph.main(BuildGraph.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.graphframes.GraphFrame$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more

**Comment by rekhajoshm** [comment]
Hi @myDemoMike The NoClassDefFoundError originates from SparkSubmit when it fails to load your  class. Is your graphframes jar present in the path at runtime? If not, you can download the relevant graphframes jar from https://spark-packages.org/package/graphframes/graphframes and use --jars to upload it as a dependency on your cluster.

**Comment by dhanur8** [comment]
@myDemoMike  Were you able to fix this issue ? @rekhajoshm Did you mean something like , first download the relevant graphframe and save it in aws-S3 and then type --jars "path" in spark submit options ?  I am also getting the same issue as mentioned here.

**Comment by SemyonSinchenko** [comment]
It looks outdated. I'm closing it now, feel free to re-open in case you face this issue with tha latest versions of spark and graphframes.
