### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ali3assi** [graphframes/graphframes#323]
Hello,
I want to use graphframes fo my project. 
Im using an linux SSH sever. So, To run spark, i procced as follows:
1- module load python/2.7.14
2-source "path/to/activate"
3- module load spark/2.3.0
4- spark-submit "path to myscript.py"

Normally, by using the above steps i m able to run spark without any difficuly. 

Unfortunatley, Im not able to run graphFrames. What i did is:
1- pyspark --packages graphframes:graphframes:0.6.0-spark2.3-s_2.11
 
i get the following exeption:
```
Python 2.7.14 (default, Dec  4 2017, 16:27:52)
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Ivy Default Cache set to: /home/tamouze/.ivy2/cache
The jars for the packages stored in: /home/tamouze/.ivy2/jars
:: loading settings :: url = jar:file:/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/spark/2.3.0/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
        confs: [default]
:: resolution report :: resolve 254916ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: graphframes#graphframes;0.6.0-spark2.3-s_2.11

        ==== local-m2-cache: tried

          file:/home/tamouze/.m2/repository/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          file:/home/tamouze/.m2/repository/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

        ==== local-ivy-cache: tried

          /home/tamouze/.ivy2/local/graphframes/graphframes/0.6.0-spark2.3-s_2.11/ivys/ivy.xml

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          /home/tamouze/.ivy2/local/graphframes/graphframes/0.6.0-spark2.3-s_2.11/jars/graphframes.jar

        ==== central: tried

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

        ==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: graphframes#graphframes;0.6.0-spark2.3-s_2.11: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom (java.net.ConnectException: Connection timed out (Connection timed out))

        Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar (java.net.ConnectException: Connection timed out (Connection timed out))


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.6.0-spark2.3-s_2.11: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1270)
        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:49)
        at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:350)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:170)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/spark/2.3.0/python/pyspark/shell.py", line 38, in <module>
    SparkContext._ensure_initialized()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/spark/2.3.0/python/pyspark/context.py", line 280, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/spark/2.3.0/python/pyspark/java_gateway.py", line 95, in launch_gateway
    raise Exception("Java gateway process exited before sending the driver its port number")
Exception: Java gateway process exited before sending the driver its port number
>>>

```

Any help will be so appreciated to solve this problem and use this package asap

**Comment by felixcheung** [comment]
there's no graphframes on maven central 
https://repo1.maven.org/maven2/graphframes

so that fails

http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

should work though. are you able to access http://dl.bintray.com/spark-packages/?

**Comment by TamouzeAssi** [comment]
Sorry @felixcheung , can you be more precise. Im newbie in spark

**Comment by felixcheung** [comment]
check if the computer you are running spark-submit on can see that website

**Comment by TamouzeAssi** [comment]
you mean if f can run wget
http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

if you mean that, yes i can run this command and get the .jar

**Comment by felixcheung** [comment]
hmm, not sure why this message then
```
==== spark-packages: tried

          http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.pom

          -- artifact graphframes#graphframes;0.6.0-spark2.3-s_2.11!graphframes.jar:

          http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.6.0-spark2.3-s_2.11/graphframes-0.6.0-spark2.3-s_2.11.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

```

**Comment by TamouzeAssi** [comment]
@felixcheung im trying to use install graphframes though java. But there is a problem of connection:
`[ERROR] Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-resources-plugin:jar:2.6: Could not transfer artifact org.apache.maven.plugins:maven-resources-plugin:pom:2.6 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.124.215] failed: Connection timed out (Connection timed out) -> [Help 1]`

**Comment by purohitsumit** [comment]
Hi @TamouzeAssi what do you mean by "use install graphframes through java" ? Are you using "mvn" to build your project ? Are you behind any firewall ?

**Comment by TamouzeAssi** [comment]
@purohitsumit I tried to use maven to download graphframes. Im not behind a firewall

**Comment by KeremKurban** [comment]
Any news on this ? I tried a similar thing 

`spark-3.4.0-bin-hadoop3/bin/spark-submit --packages graphframes:graphframes:0.6.0-spark3.4.0 graph_frames.py
`
and got 

```
:: loading settings :: url = jar:file:/gpfs/bbp.cscs.ch/project/proj112/home/kurban/connectome_analysis_scripts/spark-3.4.0-bin-hadoop3/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /gpfs/bbp.cscs.ch/home/kurban/.ivy2/cache
The jars for the packages stored in: /gpfs/bbp.cscs.ch/home/kurban/.ivy2/jars
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-dc041768-de2c-4933-b8fd-a62825694afd;1.0
        confs: [default]
:: resolution report :: resolve 509273ms :: artifacts dl 0ms
        :: modules in use:
        ---------------------------------------------------------------------
        |                  |            modules            ||   artifacts   |
        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
        ---------------------------------------------------------------------
        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
        ---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
                module not found: graphframes#graphframes;0.6.0-spark3.4.0

        ==== local-m2-cache: tried

          file:/gpfs/bbp.cscs.ch/home/kurban/.m2/repository/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.pom

          -- artifact graphframes#graphframes;0.6.0-spark3.4.0!graphframes.jar:

          file:/gpfs/bbp.cscs.ch/home/kurban/.m2/repository/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.jar

        ==== local-ivy-cache: tried

          /gpfs/bbp.cscs.ch/home/kurban/.ivy2/local/graphframes/graphframes/0.6.0-spark3.4.0/ivys/ivy.xml

          -- artifact graphframes#graphframes;0.6.0-spark3.4.0!graphframes.jar:

          /gpfs/bbp.cscs.ch/home/kurban/.ivy2/local/graphframes/graphframes/0.6.0-spark3.4.0/jars/graphframes.jar

        ==== central: tried

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.pom

          -- artifact graphframes#graphframes;0.6.0-spark3.4.0!graphframes.jar:

          https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.jar

        ==== spark-packages: tried

          https://repos.spark-packages.org/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.pom

          -- artifact graphframes#graphframes;0.6.0-spark3.4.0!graphframes.jar:

          https://repos.spark-packages.org/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.jar

                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: graphframes#graphframes;0.6.0-spark3.4.0: not found

                ::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
        Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.pom (java.net.ConnectException: Connection timed out (Connection timed out))

        Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.jar (java.net.ConnectException: Connection timed out (Connection timed out))

        Server access error at url https://repos.spark-packages.org/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.pom (java.net.ConnectException: Connection timed out (Connection timed out))

        Server access error at url https://repos.spark-packages.org/graphframes/graphframes/0.6.0-spark3.4.0/graphframes-0.6.0-spark3.4.0.jar (java.net.ConnectException: Connection timed out (Connection timed out))


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.6.0-spark3.4.0: not found]
        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1528)
        at org.apache.spark.util.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:185)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:332)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:192)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:215)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1111)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1120)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
