### ISSUE TITLE
Version 0.7.0, Spark 2.4 and JupyterHub (EMR) - ClassNotFoundException

### ISSUE THREAD

**Issue by archienorman11** [graphframes/graphframes#325]
Hi, 

Looking for some guidance getting graphframes running on jupyterhub/EMR. 

The `jar` is installed:

`graphframes-0.7.0-spark2.4-s_2.11.jar`

And in the notebook:

```
from graphframes import GraphFrame
from graphframes.lib import AggregateMessages as AM
print(GraphFrame)

<class 'graphframes.graphframe.GraphFrame'>
```

So the GraphFrame package is loading. However:

```
vertices = spark.createDataFrame([('1', 'Carter', 'Derrick', 50), ('2', 'May', 'Derrick', 26)],['id', 'name', 'firstname', 'age'])
edges = spark.createDataFrame([('1', '2', 'friend'), ('2', '1', 'friend')], ['src', 'dst', 'type'])

g = GraphFrame(vertices, edges)
g.vertices.show()
g.edges.show()
```

Results in:

```
py4j.protocol.Py4JJavaError: An error occurred while calling o121.loadClass.
: java.lang.ClassNotFoundException: org.graphframes.GraphFramePythonAPI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

Any suggestions appreciated.

**Comment by shinalone** [comment]
Same Problem !

**Comment by machielg** [comment]
How is the jar installed?
