### ISSUE TITLE
GraphFrames 0.6.0 java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by ashkan-leo** [graphframes/graphframes#354]
I am using GraphFrames 0.6.0, Spark 2.20, and Scala 2.11.12 and when I try to create a graph I get the following error:
```
[info] com.conversantmedia.dsi.matchengine.core.graph.graphTest *** ABORTED ***
[info]   java.lang.IncompatibleClassChangeError: Implementing class
[info]   at java.lang.ClassLoader.defineClass1(Native Method)
[info]   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[info]   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[info]   at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
[info]   at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
[info]   at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
[info]   at java.security.AccessController.doPrivileged(Native Method)
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   ...
```

**Comment by ashkan-leo** [comment]
Closing this issue as it was caused by incompatible libraries in the build file.
