### ISSUE TITLE
Inconsistent/DataLoss on ConnectedComponents assignment

### ISSUE THREAD

**Issue by girbeabogdan** [graphframes/graphframes#389]
Hello folks! Dropping a qq here @mengxr , @jkbradley , @thunterdb
We're using graphframes 0.6 & spark 2.4.4 and running ConnectedComponents for 335 billion edges thus generating 361 billion connected components identifiers.

We noticed the ConnectedComponents algorithm is NOT doing the CC assignment for a few vertexes **connected** by an edge. The problem looks transitive since it gets resolved by following job runs pointing to some dataloss (& using same input data)

Any ideas on why this would be happening?

**Comment by alexbigabid** [comment]
Hello,
I have the same issue.
When i'm running the code, spark throw the next exceptions:

`WARN AsyncEventQueue: Dropped 24727 events from appStatus since Sun May 30 11:20:18 UTC 2021.
21/05/30 11:22:35 WARN ServletHandler: javax.servlet.ServletException: java.lang.IndexOutOfBoundsException: 196
Caused by: java.lang.IndexOutOfBoundsException: 10
        at scala.collection.immutable.Vector.checkRangeConvert(Vector.scala:132)
        at scala.collection.immutable.Vector.apply(Vector.scala:122)
        at org.apache.spark.status.AppStatusStore$$anonfun$scanTasks$1$1.apply$mcDJ$sp(AppStatusStore.scala:295)
        at org.apache.spark.status.AppStatusStore$$anonfun$scanTasks$1$1.apply(AppStatusStore.scala:294)
        at org.apache.spark.status.AppStatusStore$$anonfun$scanTasks$1$1.apply(AppStatusStore.scala:294)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofLong.foreach(ArrayOps.scala:246)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.mutable.ArrayOps$ofLong.map(ArrayOps.scala:246)
        at org.apache.spark.status.AppStatusStore.scanTasks$1(AppStatusStore.scala:294)
        at org.apache.spark.status.AppStatusStore.taskSummary(AppStatusStore.scala:327)
        at org.apache.spark.status.api.v1.StagesResource$$anonfun$taskSummary$1.apply(StagesResource.scala:90)
        at org.apache.spark.status.api.v1.StagesResource$$anonfun$taskSummary$1.apply(StagesResource.scala:80)
        at org.apache.spark.status.api.v1.BaseAppResource$$anonfun$withUI$1.apply(ApiRootResource.scala:140)
        at org.apache.spark.status.api.v1.BaseAppResource$$anonfun$withUI$1.apply(ApiRootResource.scala:135)
        at org.apache.spark.ui.SparkUI.withSparkUI(SparkUI.scala:106)
        at org.apache.spark.status.api.v1.BaseAppResource$class.withUI(ApiRootResource.scala:135)
        at org.apache.spark.status.api.v1.StagesResource.withUI(StagesResource.scala:30)
        at org.apache.spark.status.api.v1.StagesResource.taskSummary(StagesResource.scala:80)
        at sun.reflect.GeneratedMethodAccessor144.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        ... 28 more
`
Can  someone to help us?
