### ISSUE TITLE
Getting py4j.security.Py4JSecurityException on Graphframes 0.8.3 with spark 3.4.1 Scala 2.12

### ISSUE THREAD

**Issue by pandiyanpalanisamy** [graphframes/graphframes#452]
Hi,

I am trying to create Graphframe using Vertices and Edges. I am getting the following error message,
'
Py4JError                                 Traceback (most recent call last)
File <command-1564577446668161>, line 3
      1 from graphframes import GraphFrame
      2 start_time_graph_creation = time.time()
----> 3 g = GraphFrame(all_vertices, all_edges)
      4 end_time_graph_creation = time.time()
      5 graph_creation_time = end_time_graph_creation - start_time_graph_creation

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/graphframes/graphframe.py:68, in GraphFrame.__init__(self, v, e)
     66 self._spark = SparkSession.getActiveSession()
     67 self._sc = self._spark._sc
---> 68 self._jvm_gf_api = _java_api(self._sc)
     70 self.ID = self._jvm_gf_api.ID()
     71 self.SRC = self._jvm_gf_api.SRC()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/graphframes/graphframe.py:41, in _java_api(jsc)
     39 def _java_api(jsc):
     40     javaClassName = "org.graphframes.GraphFramePythonAPI"
---> 41     return jsc._jvm.Thread.currentThread().getContextClassLoader().loadClass(javaClassName) \
     42             .newInstance()

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py:1355, in JavaMember.__call__(self, *args)
   1349 command = proto.CALL_COMMAND_NAME +\
   1350     self.command_header +\
   1351     args_command +\
   1352     proto.END_COMMAND_PART
   1354 answer = self.gateway_client.send_command(command)
-> 1355 return_value = get_return_value(
   1356     answer, self.gateway_client, self.target_id, self.name)
   1358 for temp_arg in temp_args:
   1359     if hasattr(temp_arg, "_detach"):

File /databricks/spark/python/pyspark/errors/exceptions/captured.py:188, in capture_sql_exception.<locals>.deco(*a, **kw)
    186 def deco(*a: Any, **kw: Any) -> Any:
    187     try:
--> 188         return f(*a, **kw)
    189     except Py4JJavaError as e:
    190         converted = convert_exception(e.java_exception)

File /databricks/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py:330, in get_return_value(answer, gateway_client, target_id, name)
    326         raise Py4JJavaError(
    327             "An error occurred while calling {0}{1}{2}.\n".
    328             format(target_id, ".", name), value)
    329     else:
--> 330         raise Py4JError(
    331             "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
    332             format(target_id, ".", name, value))
    333 else:
    334     raise Py4JError(
    335         "An error occurred while calling {0}{1}{2}".
    336         format(target_id, ".", name))

Py4JError: An error occurred while calling o456.loadClass. Trace:
py4j.security.Py4JSecurityException: Method public java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) throws java.lang.ClassNotFoundException is not whitelisted on class class com.databricks.backend.daemon.driver.DriverCorral$DriverCorralClassLoader
	at py4j.security.WhitelistingPy4JSecurityManager.checkCall(WhitelistingPy4JSecurityManager.java:473)
	at py4j.Gateway.invoke(Gateway.java:305)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:199)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:119)
	at java.lang.Thread.run(Thread.java:750)

Kindly help me with this

**Comment by pandiyanpalanisamy** [comment]
This issue happened because of the spark configuration.
