### ISSUE TITLE
Py4JJavaError: An error occurred while calling o57.find.

### ISSUE THREAD

**Issue by napsternxg** [graphframes/graphframes#56]
I am using `graphframes:graphframes:0.1.0-spark1.6` from the **pyspark** interface with **current master build of Spark**. I get the following error when I am trying to use the `g.find` functions and other functions as shown in the example notebook at: http://go.databricks.com/hubfs/notebooks/3-GraphFrames-User-Guide-python.html

```
In [16]: motifs = g.find("(a)-[e]->(b); (b)-[e2]->(a)")
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-16-ac1d920bb1a7> in <module>()
----> 1 motifs = g.find("(a)-[e]->(b); (b)-[e2]->(a)")

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in find(self, pattern)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o57.find.
: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
        at org.graphframes.GraphFrame.findSimple(GraphFrame.scala:370)
        at org.graphframes.GraphFrame.find(GraphFrame.scala:263)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

In [17]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:paths = g.find("(a)-[e]->(b)")\
:  .filter("e.relationship = 'follow'")\
:  .filter("a.age < b.age")
:# The `paths` variable contains the vertex information, which we can extract:
:e2 = paths.select("e.src", "e.dst", "e.relationship")
:
:# In Spark 1.5+, the user may simplify the previous call to:
:# val e2 = paths.select("e.*")
:
:# Construct the subgraph
:g2 = GraphFrame(g.vertices, e2)
:--
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-17-7411759ff966> in <module>()
----> 1 paths = g.find("(a)-[e]->(b)")  .filter("e.relationship = 'follow'")  .filter("a.age < b.age")
      2 # The `paths` variable contains the vertex information, which we can extract:
      3 e2 = paths.select("e.src", "e.dst", "e.relationship")
      4 
      5 # In Spark 1.5+, the user may simplify the previous call to:

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in find(self, pattern)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o57.find.
: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
        at org.graphframes.GraphFrame.findSimple(GraphFrame.scala:370)
        at org.graphframes.GraphFrame.find(GraphFrame.scala:263)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

```

Also, when using the function BFS, ConnectedComponents, LabelPropagation, triangleCount, shortestPaths, pageRank, stronglyConnectedComponents, I get the following errors about the Methods not implemented. 

```
In [18]: paths = g.bfs("name = 'Esther'", "age < 32")
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-18-90070d1d699a> in <module>()
----> 1 paths = g.bfs("name = 'Esther'", "age < 32")

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in bfs(self, fromExpr, toExpr, edgeFilter, maxPathLength)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o101.run.
: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
        at org.graphframes.GraphFrame.findSimple(GraphFrame.scala:370)
        at org.graphframes.GraphFrame.find(GraphFrame.scala:263)
        at org.graphframes.lib.BFS$.org$graphframes$lib$BFS$$run(BFS.scala:159)
        at org.graphframes.lib.BFS.run(BFS.scala:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [19]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:filteredPaths = g.bfs(
:  fromExpr = "name = 'Esther'",
:  toExpr = "age < 32",
:  edgeFilter = "relationship != 'friend'",
:  maxPathLength = 3)
:--
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-19-9a217d29ca2a> in <module>()
      3   toExpr = "age < 32",
      4   edgeFilter = "relationship != 'friend'",
----> 5   maxPathLength = 3)

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in bfs(self, fromExpr, toExpr, edgeFilter, maxPathLength)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o122.run.
: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
        at org.graphframes.GraphFrame.findSimple(GraphFrame.scala:370)
        at org.graphframes.GraphFrame.find(GraphFrame.scala:263)
        at org.graphframes.lib.BFS$.org$graphframes$lib$BFS$$run(BFS.scala:159)
        at org.graphframes.lib.BFS.run(BFS.scala:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [20]: result = g.connectedComponents()
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-20-7eb76cabdc93> in <module>()
----> 1 result = g.connectedComponents()

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in connectedComponents(self)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o141.run.
: java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrame.map(Lscala/Function1;Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/RDD;
        at org.graphframes.GraphFrame.toGraphX(GraphFrame.scala:136)
        at org.graphframes.GraphFrame.cachedGraphX$lzycompute(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedGraphX(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedTopologyGraphX$lzycompute(GraphFrame.scala:432)
        at org.graphframes.GraphFrame.cachedTopologyGraphX(GraphFrame.scala:431)
        at org.graphframes.lib.ConnectedComponents$.run(ConnectedComponents.scala:50)
        at org.graphframes.lib.ConnectedComponents.run(ConnectedComponents.scala:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [21]: g.vertices
Out[21]: DataFrame[id: string, name: string, age: bigint]

In [22]: g.vertices.show()
+---+-------+---+
| id|   name|age|
+---+-------+---+
|  a|  Alice| 34|
|  b|    Bob| 36|
|  c|Charlie| 30|
|  d|  David| 29|
|  e| Esther| 32|
|  f|  Fanny| 36|
|  g|  Gabby| 60|
+---+-------+---+


In [23]: result = g.stronglyConnectedComponents(maxIter=10)
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-23-9cbad8f66c11> in <module>()
----> 1 result = g.stronglyConnectedComponents(maxIter=10)

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in stronglyConnectedComponents(self, maxIter)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o163.run.
: java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrame.map(Lscala/Function1;Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/RDD;
        at org.graphframes.GraphFrame.toGraphX(GraphFrame.scala:136)
        at org.graphframes.GraphFrame.cachedGraphX$lzycompute(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedGraphX(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedTopologyGraphX$lzycompute(GraphFrame.scala:432)
        at org.graphframes.GraphFrame.cachedTopologyGraphX(GraphFrame.scala:431)
        at org.graphframes.lib.StronglyConnectedComponents$.org$graphframes$lib$StronglyConnectedComponents$$run(StronglyConnectedComponents.scala:52)
        at org.graphframes.lib.StronglyConnectedComponents.run(StronglyConnectedComponents.scala:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [24]: result = g.labelPropagation(maxIter=5)
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-24-d841648f0e34> in <module>()
----> 1 result = g.labelPropagation(maxIter=5)

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in labelPropagation(self, maxIter)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o185.run.
: java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrame.map(Lscala/Function1;Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/RDD;
        at org.graphframes.GraphFrame.toGraphX(GraphFrame.scala:136)
        at org.graphframes.GraphFrame.cachedGraphX$lzycompute(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedGraphX(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedTopologyGraphX$lzycompute(GraphFrame.scala:432)
        at org.graphframes.GraphFrame.cachedTopologyGraphX(GraphFrame.scala:431)
        at org.graphframes.lib.LabelPropagation$.org$graphframes$lib$LabelPropagation$$run(LabelPropagation.scala:63)
        at org.graphframes.lib.LabelPropagation.run(LabelPropagation.scala:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [25]: results = g.pageRank(resetProbability=0.15, tol=0.01)
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-25-7ba4099c0dbc> in <module>()
----> 1 results = g.pageRank(resetProbability=0.15, tol=0.01)

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in pageRank(self, resetProbability, sourceId, maxIter, tol)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o208.run.
: java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrame.map(Lscala/Function1;Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/RDD;
        at org.graphframes.GraphFrame.toGraphX(GraphFrame.scala:136)
        at org.graphframes.GraphFrame.cachedGraphX$lzycompute(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedGraphX(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedTopologyGraphX$lzycompute(GraphFrame.scala:432)
        at org.graphframes.GraphFrame.cachedTopologyGraphX(GraphFrame.scala:431)
        at org.graphframes.lib.PageRank$.runUntilConvergence(PageRank.scala:153)
        at org.graphframes.lib.PageRank.run(PageRank.scala:102)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [26]: results = g.shortestPaths(landmarks=["a", "d"])
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-26-05cc91bf2d89> in <module>()
----> 1 results = g.shortestPaths(landmarks=["a", "d"])

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in shortestPaths(self, landmarks)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o231.run.
: java.lang.NoSuchMethodError: org.apache.spark.sql.DataFrame.map(Lscala/Function1;Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/RDD;
        at org.graphframes.GraphFrame.toGraphX(GraphFrame.scala:136)
        at org.graphframes.GraphFrame.cachedGraphX$lzycompute(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedGraphX(GraphFrame.scala:438)
        at org.graphframes.GraphFrame.cachedTopologyGraphX$lzycompute(GraphFrame.scala:432)
        at org.graphframes.GraphFrame.cachedTopologyGraphX(GraphFrame.scala:431)
        at org.graphframes.lib.ShortestPaths$.org$graphframes$lib$ShortestPaths$$run(ShortestPaths.scala:69)
        at org.graphframes.lib.ShortestPaths.run(ShortestPaths.scala:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


In [27]: results = g.triangleCount()
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-27-8e965378aa62> in <module>()
----> 1 results = g.triangleCount()

/content/tmp/spark-e344f1b3-a40f-488a-9cef-57049b7b3a04/userFiles-54d9528e-17fa-4a53-907e-dc4eca1da328/graphframes_graphframes-0.1.0-spark1.6.jar/graphframes/graphframe.pyc in triangleCount(self)

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/java_gateway.py in __call__(self, *args)
    833         answer = self.gateway_client.send_command(command)
    834         return_value = get_return_value(
--> 835             answer, self.gateway_client, self.target_id, self.name)
    836 
    837         for temp_arg in temp_args:

/content/SOFTWARE/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     43     def deco(*a, **kw):
     44         try:
---> 45             return f(*a, **kw)
     46         except py4j.protocol.Py4JJavaError as e:
     47             s = e.java_exception.toString()

/content/SOFTWARE/spark/python/lib/py4j-0.9.1-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    308                 raise Py4JJavaError(
    309                     "An error occurred while calling {0}{1}{2}.\n".
--> 310                     format(target_id, ".", name), value)
    311             else:
    312                 raise Py4JError(

Py4JJavaError: An error occurred while calling o252.run.
: java.lang.NoSuchMethodError: scala.collection.immutable.$colon$colon.hd$1()Ljava/lang/Object;
        at org.graphframes.GraphFrame.findSimple(GraphFrame.scala:370)
        at org.graphframes.GraphFrame.find(GraphFrame.scala:263)
        at org.graphframes.lib.TriangleCount$.org$graphframes$lib$TriangleCount$$run(TriangleCount.scala:58)
        at org.graphframes.lib.TriangleCount.run(TriangleCount.scala:39)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:290)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by mengxr** [comment]
`graphframes:graphframes:0.1.0-spark1.6` was compiled with Spark 1.6.0 and Scala 2.10.5. From the error messages, you are using Spark master, which contains some breaking API changes (like `DataFrame.map` is now `DataFrame.rdd.map`). So you should try the examples with the official Spark 1.6.0 release on Scala 2.10.

**Comment by jkbradley** [comment]
Just to let you know, I've been maintaining a merged branch with 2.0, but there are still issues with it b/c of flux in master.  I'll close this issue, but please stay tuned for a 2.0 release once Spark 2.0 is out!

**Comment by napsternxg** [comment]
@jkbradley I look forward to it. BTW can you point me to the branch where you are working on the 2.0 version. I would want to try that out and contribute to it.

**Comment by jkbradley** [comment]
I should qualify my claim: I've been maintaining this branch: [https://github.com/jkbradley/graphframes/tree/joinelimination]  which merges Ankur's join elimination optimizations with master.  It currently is not working completely, but Ankur is taking a look at it.  Depending on how merging his optimizations goes, I may create a new branch for making this work with 2.0.  I'll update before long, thanks!

**Comment by nadavw** [comment]
I get the same error trying to use pyspark: Version: 0.2.0-spark1.6-s_2.10
scala>  util.Properties.versionString
res0: String = version 2.10.5
scala> sc.version
res2: String = 1.6.1

any recomendation what can be done?

**Comment by jkbradley** [comment]
@nadavw Thanks for reporting this!  I tried out that GraphFrames release with Spark 1.6 and found:
* It works with 1.6.2
* It fails (with a similar error) with 1.6.1

In the short term, can you upgrade to 1.6.2 or 2.0.0?  In the long term, I'll see if we can fix it!
